# Generated by Django 3.2 on 2021-04-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
